name: Build Docker and Test

env:
  NEXT_PUBLIC_API_URL: ${{secrets.NEXT_PUBLIC_API_URL}}

on:
  pull_request:
    branches: ['main']

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - run: npm install
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          build: npm run build
          start: npm run start
          browser: chrome
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Just Build
        uses: docker/build-push-action@v4
        with:
          push: false
          tags: ${{ secrets.APP_IMAGE }}
          build-args: NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}
