name: Build and Test

on:
  pull_request:
    branches: [ 'main' ]

jobs:
  Testing:
    runs-on: ubuntu-latest
    environment: testing
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          load: true
          tags: ${{ secrets.APP_IMAGE }}
          build-args: NEXT_PUBLIC_API_URL=${{ vars.NEXT_PUBLIC_API_URL }}
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          start: docker run --name my-makeup -p 3000:3000 -d --env "ENV=development" --env "NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }}" --env "NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL }}" --env "NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}" --env "NEXT_PUBLIC_URL=${{ secrets.NEXT_PUBLIC_URL }}"  --env "NEXT_PUBLIC_DATABASE_URL=${{ secrets.NEXT_PUBLIC_DATABASE_URL }}" --env "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" --env "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}" --env "FACEBOOK_CLIENT_ID=${{ secrets.FACEBOOK_CLIENT_ID }}" --env "FACEBOOK_CLIENT_SECRET=${{ secrets.FACEBOOK_CLIENT_SECRET }}" --env "MAILGUN_API_KEY=${{ secrets.MAILGUN_API_KEY }}" --env "MAILGUN_API_URL=${{ secrets.MAILGUN_API_URL }}" --env "MAILGUN_PUBLIC_KEY=${{ secrets.MAILGUN_PUBLIC_KEY }}" --env "MAILGUN_DOMAIN=${{ secrets.MAILGUN_DOMAIN }}" --env "CYPRESS_TEST_USER=${{ secrets.TEST_USER }}" --env "CYPRESS_TEST_PW=${{ secrets.TEST_PW }}"  ${{ secrets.APP_IMAGE }}
          browser: chrome
          wait-on: 'http://localhost:3000'
          env:
            ENV=development
            NEXT_PUBLIC_API_URL=${{ vars.NEXT_PUBLIC_API_URL }}
            NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }}
            NEXT_PUBLIC_URL=${{ secrets.NEXT_PUBLIC_URL }}
            NEXT_PUBLIC_DATABASE_URL=${{ secrets.NEXT_PUBLIC_DATABASE_URL }}
            NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL }}
            GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}
            GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}
            FACEBOOK_CLIENT_ID=${{ secrets.FACEBOOK_CLIENT_ID }}
            FACEBOOK_CLIENT_SECRET=${{ secrets.FACEBOOK_CLIENT_SECRET }}
            MAILGUN_API_KEY=${{ secrets.MAILGUN_API_KEY }}
            MAILGUN_API_URL=${{ secrets.MAILGUN_API_URL }}
            MAILGUN_PUBLIC_KEY=${{ secrets.MAILGUN_PUBLIC_KEY }}
            MAILGUN_DOMAIN=${{ secrets.MAILGUN_DOMAIN }}
            CYPRESS_TEST_USER=${{ secrets.TEST_USER }}
            CYPRESS_TEST_PW=${{ secrets.TEST_PW }}
      - uses: actions/upload-artifact@v3
        # add the line below to store screenshots only on failures
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore # 'warn' or 'error' are also available, defaults to `warn`
      - uses: actions/upload-artifact@v3
        # add the line below to store screenshots only on failures
        if: failure()
        with:
          name: cypress-videos
          path: cypress/videos
          if-no-files-found: ignore # 'warn' or 'error' are also available, defaults to `warn`

