name: Just Build Docker

env:
  NEXT_PUBLIC_API_URL: ${{secrets.NEXT_PUBLIC_API_URL}}

on:
  pull_request:
    branches: ['main']

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Just Build
        uses: docker/build-push-action@v4
        with:
          push: false
          tags: ${{ secrets.APP_IMAGE }}
          build-args: NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}
